# Current Version: 1.0.0

name: Build & Release hezhijie0327/E5Renew

on:
    push:
        branches: [main]
    schedule:
        - cron: "0 */6 * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v2.3.4
            - name: Step 2 - Setup Python Environment
              uses: actions/setup-python@v2
            - name: Step 3 - Install requests
              run: |
                  sudo pip install requests
            - name: Step 4 - Build E5Renew
              run: |
                  curl -s "https://raw.githubusercontent.com/hezhijie0327/E5Renew/source/E5Renew.py" | sed "s/config\_client\_id/${{ secrets.config_client_id }}/g;s/config\_client\_secret/${{ secrets.config_client_secret }}/g" > "./E5Renew.py"
                  sudo python "./E5Renew.py"
                  sudo rm -rf "./E5Renew.py"
            - name: Step 5 - Release E5Renew
              run: |
                  sudo git config user.name github-actions
                  sudo git config user.email github-actions@github.com
                  sudo git add .
                  sudo git commit -m "Generated by GitHub Actions"
                  sudo git push --force
